[build]
  # Keep execution context at the absolute root level
  base = ""
  
  # Explicitly tell Next.js where the application folder sits
  command = "cross-env NEXT_IGNORE_DEV_WARNINGS=1 next build client"
  publish = "client/.next"

[build.environment]
  NEXT_IGNORE_DEV_WARNINGS = "1"